In [1]:
import io
import cv2 as cv2
import numpy as np
from IPython.display import clear_output, Image, display
import PIL.Image
from matplotlib import pyplot as plt
from numpy import load

показываем картинку

In [2]:
def image_show(img):
    scale_percent = 60
    width = int(img.shape[1] * scale_percent / 100)
    height = int(img.shape[0] * scale_percent / 100)
    dm = (width, height)
    img = cv2.resize(img, dm, interpolation = cv2.INTER_AREA)

    cv2.imshow("Result", img)  #желтый - 255,235,0; зеленый - 0,255,0; красныый - 255, 0, 0, голубой - 0,246,255
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Цикл, который перебирает пороги

In [3]:
def thresh(img):
    lst = [i for i in range(1,200+20,20)]
    for x in lst:
        ret,th1 = cv2.threshold(img,x,255,cv2.THRESH_BINARY)
        #plt.imshow(th1,'gray')
        titles = ['Original Image', 'Global Thresholding v='+str(x)]
        images = [img, th1]
        for i in range(2):
            plt.subplot(1,2,i+1),plt.imshow(images[i],'gray')
            plt.title(titles[i])
            plt.xticks([]),plt.yticks([])
        plt.show()

In [4]:
def contour_find(image1,parameter1, parameter2):
    img_gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
    ret, thresh1 = cv2.threshold(img_gray1, parameter1, parameter2, cv2.THRESH_BINARY)
    contours2, hierarchy2 = cv2.findContours(thresh1, cv2.RETR_TREE,
                                                   cv2.CHAIN_APPROX_SIMPLE)
    image_copy2 = image1.copy()
    cv2.drawContours(image_copy2, contours2, -1, (0, 255, 0), 2, cv2.LINE_AA)
    return image_copy2

In [5]:
def find_skul(img):
    skul_1 = np.array([198, 204, 184])
    skul_2 = np.array([229, 229, 229])
    mask = cv2.inRange(img, skul_1, skul_2)
    result = cv2.bitwise_and(img, img, mask=mask)
    return result

424 - 482 высота модельки
433 - 440, 811 - 816 - глаз

In [6]:
def get_eye(img):
    eye = img[433:440, 811:817]
    print(eye)
    #eye = cv2.cvtColor(eye, cv2.COLOR_RGB2GRAY)
    cv2.imwrite('screens/eye.png',eye)
    image_show(eye)
    return eye

In [7]:
def get_model(img):
    img_g = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY).astype(np.float32)
    eye = cv2.imread('screens/eye.png')
    eye = cv2.cvtColor(eye, cv2.COLOR_RGB2GRAY)
    result = cv2.matchTemplate(img_g, eye.astype(np.float32), cv2.TM_CCOEFF_NORMED)
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
    threshold = 0.8  # Adjust this value based on your specific use case

    if max_val >= threshold:
        print("ROI is present in the original image.")
    else:
        print("ROI is not present in the original image.")

In [8]:
image = cv2.imread('screens/ikran.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_show(image)
eye = get_eye(image)
contours = contour_find(image, 60, 255)
#image_show(contours)


get_model(image)


[[[145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]]

 [[145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]]

 [[145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]]

 [[145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]]

 [[145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]]

 [[145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]]

 [[145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]
  [145 195 255]]]
